# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: phperrot <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/18 19:43:51 by phperrot          #+#    #+#              #
#    Updated: 2018/07/20 16:34:59 by phperrot         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all: compilation

compilation: 
	gcc -Wall -Wextra -Werror main.c ft_functions.c ft_display_functions.c -I ft_header.h -I ft_opp.h -o do-op

clean:
	rm -f do-op


