# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: phperrot <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/20 13:27:18 by phperrot          #+#    #+#              #
#    Updated: 2018/07/20 13:47:36 by phperrot         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all: compilation

compilation:
	gcc *c -o ft_display_file

clean:
	rm ft_display_file

fclean:
	rm ft_display_file
